import boto3
from botocore.exceptions import ClientError

# Crear un cliente para DynamoDB
dynamodb = boto3.resource('dynamodb', region_name='us-west-2')
table = dynamodb.Table('pruebafinalaws')

try:
    # A침adir un nuevo elemento para generar un evento
    response = table.put_item(
        Item={
            'Id': '2',     # Clave de partici칩n
            'Date': '2024-01-01',  # Clave de clasificaci칩n, usando formato de fecha como ejemplo
            'OtherAttribute': 'Valor de prueba2'  # Otros atributos adicionales
        }
    )
    print("Elemento a침adido:", response)

except ClientError as e:
    print(f"Error al manipular la tabla: {e}")
